### PR TITLE
Update build script for MSVC tools

### PR DESCRIPTION
**Pull request by elasota**

### CODE REVIEW

**Comment by sfiera** [comment]
That change to gn-tools is larger than I would have expected. I may have made changes without yet updating for them here.

**Comment by elasota** [comment]
I'm guessing it doesn't need to be updated for when it's being compiled from another project?  I'll just take it out I guess.

**Comment by sfiera** [comment]
Yep. I will handle updating gn-tools; it should be fine to omit here.

**Comment by elasota** [comment]
Changed to just update BUILD.gn

**Pull request merged**
