### PR TITLE
Support u/U codes in pn_set()

### PR DESCRIPTION
**Pull request by sfiera**
These treat the source data as uint16_t or uint32_t with a size_t count. Currently, uint32_t data is correctly treated as UTF-32, but the uint16_t data is incorrectly treated as UCS-2, rather than UTF-16.

### CODE REVIEW

**Comment by sfiera** [comment]
@elasota This includes some more native UTF-16/32 support along the lines of what I’m thinking. The main things missing are:
* Proper UTF-16 support (your work is good and I would be happy to let you handle this or take it over as you’d prefer)
* A method `std::u16string pn::string::cpp_str16() const` for getting a UTF-16 string back out (and probably a C equivalent)

**Comment by elasota** [comment]
Hmm, should be able to use char16_t/char32_t even in C instead of uint16_t/uint32_t, right?

**Comment by sfiera** [comment]
Not on Mac, it seems. For some reason, Apple doesn’t ship `uchar.h`. On the other hand, since they are supposed to be typedefs of `uint_least{16,32}_t`, perhaps it would be more correct to use those, ugly as they may be.

**Comment by elasota** [comment]
I guess since in conversion between C++ standard strings and Procyon strings, it's going to need to allocate a result buffer either way, could just "convert" between uint16_t/char16_t then.  In cases where it's the same size (which should be nearly always), just memcpy.

**Comment by sfiera** [comment]
I have something I think I’m satisfied with, though I’ve apparently got a problem compiling some gmock tests on Windows. The `std::ostream` printers for `u{16,32}string` appear to be explicitly deleted, which confuses gmock.

**Comment by elasota** [comment]
Maybe another reason to update gtest.  Newest version has overloads for the Unicode char and string types:
https://github.com/google/googletest/blob/main/googletest/include/gtest/gtest-printers.h

**Comment by sfiera** [comment]
Ah, that’s good. I’ll give it a go.

**Pull request merged**
